/* Bilingual local prototype. All external actions are intentionally absent. */
(function () {
'use strict';
const C=ClubCore, KEY='simpliigood.creatorclub.v1', PREF='simpliigood.creatorclub.prefs';
const $=sel=>document.querySelector(sel);
const e=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const safeJSON=v=>JSON.stringify(v,null,2);
let loadError='', prefs={};
try{prefs=JSON.parse(localStorage.getItem(PREF)||'{}');}catch(_){}
let lang=prefs.lang==='en'?'en':'he', view='admin', page='dashboard', market='all', search='', creatorId='c3', modalReturnFocus=null;
const query=new URLSearchParams(location.search);if(query.get('lang')==='en')lang='en';if(query.get('view')==='creator')view='creator';if(query.get('view')==='apply')view='apply';
let state;
try {const raw=localStorage.getItem(KEY);state=raw?JSON.parse(raw):C.createSeed();C.validateState(state);}catch(err){state=C.createSeed();loadError='invalidBackup';}
function t(k){return TRANSLATIONS[lang][k]||k;}
const title=m=>C.titleText(m,lang,TRANSLATIONS), brief=m=>C.briefText(m,lang,TRANSLATIONS);
const money=(v,cur)=>new Intl.NumberFormat(lang==='he'?'he-IL':'en-US',{style:'currency',currency:cur,minimumFractionDigits:0,maximumFractionDigits:2}).format(v);
const fm=(v,cur)=>'<bdi dir="ltr">'+e(money(v,cur))+'</bdi>';
const number=v=>new Intl.NumberFormat(lang==='he'?'he-IL':'en-US').format(v);
const date=v=>{try{return new Intl.DateTimeFormat(lang==='he'?'he-IL':'en-US',{day:'numeric',month:'short'}).format(new Date(v.includes('T')?v:v+'T12:00:00'));}catch(_){return e(v);}};
const marketName=m=>t(m==='IL'?'israel':'usa');
const forMarket=m=>market==='all'||m===market;
const getMission=id=>state.missions.find(m=>m.id===id), getCreator=id=>state.creators.find(c=>c.id===id);
const statusPill=s=>'<span class="status '+e(s)+'">'+e(t(s))+'</span>';
const initials=name=>name.split(/[\s/]+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();
const avatar=c=>'<span class="avatar '+(c.market==='IL'?'gold':'')+'">'+e(initials(c.name))+'</span>';
const icons={
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M21 21v-3a6 6 0 0 0-4-5.7"/>',
 brief:'<rect x="3" y="6" width="18" height="15" rx="2"/><path d="M8 6V3h8v3M3 12h18M10 11v3h4v-3"/>',
 check:'<path d="m5 12 4 4L19 6"/><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h9"/>',
 wallet:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 8h18M16 12h5v5h-5a2.5 2.5 0 0 1 0-5Z"/>',
 settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3" fill="currentColor" stroke="none"/><circle cx="16" cy="17" r="3" fill="currentColor" stroke="none"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
 leaf:'<path d="M20 4c-12-2-18 5-14 12S22 17 20 4ZM5 21 16 9"/>',
 video:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="m10 8 6 4-6 4Z"/>',
 book:'<path d="M12 5c-4-3-7-2-10-1v15c3-1 6-2 10 1 4-3 7-2 10-1V4c-3-1-6-2-10 1Zm0 0v15"/>',
 bag:'<path d="M5 7h14l2 14H3L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 x:'<path d="m6 6 12 12M6 18 18 6"/>',
 menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',
 globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z"/>',
 external:'<path d="M14 3h7v7M10 14 21 3M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"/>',
 sparkle:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3Z"/>'
};
function icon(name){return '<svg class="icon '+(name==='arrow'?'arrow-icon':'')+'" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(icons[name]||icons.leaf)+'</svg>';}
function btn(label,action,data='',cls=''){return '<button type="button" class="btn '+cls+'" data-action="'+action+'" '+data+'>'+e(t(label))+'</button>';}
function field(label,name,value='',type='text',opts=''){return '<div class="field"><label for="'+e(name)+'">'+e(t(label))+'</label><input id="'+e(name)+'" name="'+e(name)+'" type="'+type+'" value="'+e(value)+'" '+opts+'></div>';}
function select(label,name,choices,value){return '<div class="field"><label for="'+e(name)+'">'+e(t(label))+'</label><select id="'+e(name)+'" name="'+e(name)+'">'+choices.map(([v,l])=>'<option value="'+e(v)+'" '+(v===value?'selected':'')+'>'+e(l)+'</option>').join('')+'</select></div>';}
function checkbox(name,label){return '<label class="check"><input type="checkbox" name="'+e(name)+'"> <span>'+e(t(label))+'</span></label>';}
function link(url,label){try{url=C.https(url);}catch(_){return ''; }return '<a class="btn secondary sm" href="'+e(url)+'" target="_blank" rel="noopener noreferrer">'+icon('external')+e(t(label))+'</a>';}
const marketTabs=()=>'<div class="filter-tabs" aria-label="'+e(t('market'))+'">'+['all','IL','US'].map(m=>'<button class="'+(market===m?'active':'')+'" data-action="market" data-market="'+m+'">'+e(m==='all'?t('all'):marketName(m))+'</button>').join('')+'</div>';
const empty=()=>'<div class="empty">'+icon('leaf')+'<p style="margin-top:12px">'+e(t('noResults'))+'</p></div>';
function persist(next){try{localStorage.setItem(KEY,safeJSON(next));state=next;return true;}catch(_){state=next;toast(t('storageFailed'),true);return false;}}
function act(command,payload,actor){
  try{
    try{const raw=localStorage.getItem(KEY);if(raw){const latest=JSON.parse(raw);C.validateState(latest);if(latest.revision>state.revision)state=latest;}}catch(_){}
    const next=C.dispatch(state,command,payload,actor||{role:view==='creator'?'creator':'admin',creatorId});persist(next);closeModal();render();toast(t(actionSuccess(command)));return true;
  }catch(err){modalError(t(err.message)||err.message);return false;}
}
function actionSuccess(command){const m={'creator.apply':'applicationSaved','creator.approve':'applicantSaved','assignment.offer':'reserveSuccess','mission.create':'missionCreated','assignment.decline':'declined'};return m[command]||'saved';}
function actionLabel(command){return t({'creator.apply':'signup','creator.approve':'approveCreator','creator.verify':'verifyMetrics','mission.create':'newMission','assignment.offer':'offer','assignment.accept':'acceptOffer','assignment.decline':'decline','assignment.submit':'submitContent','assignment.review':'approval','assignment.publish':'publication','assignment.verify':'verifyPublication','assignment.record':'recordPayment','assignment.cancel':'cancelWork','settings.rates':'rates','demoData':'demoData'}[command]||command);}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.add('hide'),5000);}
function modalError(message){const target=$('#modal-errors');if(target){target.textContent=message;target.classList.remove('hide');target.scrollIntoView({block:'nearest'});}else toast(message,true);}
function openModal(heading,body,wide=false){
  modalReturnFocus=document.activeElement;
  $('#modal-root').innerHTML='<div class="modal-backdrop" data-overlay="true"><section class="modal '+(wide?'wide-modal':'')+'" role="dialog" aria-modal="true" aria-labelledby="modal-heading"><div class="modal-header"><h2 id="modal-heading">'+e(heading)+'</h2><button class="close-btn" data-action="close" aria-label="'+e(t('close'))+'">'+icon('x')+'</button></div><div class="modal-body"><div id="modal-errors" class="inline-error hide" role="alert"></div>'+body+'</div></section></div>';
  document.body.classList.add('modal-open');setTimeout(()=>$('#modal-root button, #modal-root input, #modal-root select')?.focus(),0);
}
function closeModal(){const had=!!$('#modal-root').innerHTML;$('#modal-root').innerHTML='';document.body.classList.remove('modal-open');if(had&&modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function render(){
 document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';
 try{localStorage.setItem(PREF,JSON.stringify({lang}));}catch(_){}
 if(view==='apply'){renderApply();return;}
 const pending=state.assignments.filter(a=>['submitted','published'].includes(a.status)).length;
 const nav=[['dashboard','grid'],['creators','users'],['missions','brief'],['review','check'],['payments','wallet'],['settings','settings']];
 $('#app').innerHTML='<aside class="sidebar" id="sidebar"><div><div class="brandmark" aria-label="SimpliiGood">Simplii<span>Good</span></div><div class="brand-sub">CREATOR CLUB</div></div><div class="side-divider"></div><span class="eyebrow" style="color:#8eaca8;font-size:9px">'+e(t('pilot'))+'</span><nav aria-label="'+e(t('admin'))+'">'+nav.map(([p,i])=>'<button data-action="nav" data-page="'+p+'" class="nav-item '+(page===p&&view==='admin'?'active':'')+'">'+icon(i)+e(t(p))+(p==='review'&&pending?'<span class="nav-count">'+pending+'</span>':'')+'</button>').join('')+'</nav><div class="side-bottom"><div class="side-note"><span class="dot"></span> '+e(t('offline'))+'<div style="margin-top:10px;font-size:11px">'+e(t('brandSafe'))+'</div></div><button class="nav-item" data-action="apply">'+icon('users')+e(t('openApplication'))+'</button><div class="side-footer">'+e(t('fresh'))+'</div></div></aside><div class="app-shell"><header class="topbar"><div class="row-start"><button class="menu-toggle" data-action="menu" aria-label="'+e(t('mobileNav'))+'">'+icon('menu')+'</button><div class="top-title"><strong style="font-size:13px">'+e(t(view==='creator'?'creator':page))+'</strong><div class="tiny muted">SIMPLIIGOOD / CREATOR CLUB</div></div></div><div class="top-actions"><span class="demo-pill"><span class="dot"></span>'+e(t('demo'))+'</span><div class="mode-switch" aria-label="'+e(t('viewMode'))+'"><button data-action="mode" data-view="admin" class="'+(view==='admin'?'active':'')+'">'+e(t('admin'))+'</button><button data-action="mode" data-view="creator" class="'+(view==='creator'?'active':'')+'">'+e(t('creator'))+'</button></div><button class="lang-btn" data-action="lang" aria-label="Change language">'+(lang==='he'?'EN':'HE')+'</button></div></header><main class="content" id="main-content"><div class="demo-banner">'+icon('shield')+'<span>'+e(t('demoBanner'))+'</span></div>'+(view==='creator'?creatorPage():({dashboard:dashboardPage,creators:creatorsPage,missions:missionsPage,review:reviewPage,payments:paymentsPage,settings:settingsPage}[page]||dashboardPage)())+'<footer class="footer"><span class="ltr">'+e(t('footer'))+'</span><span>v0.1 / '+e(t('savedLocally'))+'</span></footer></main></div>';
}
function pageTitle(key,sub,action=''){return '<div class="page-title"><div><h1>'+e(t(key))+'</h1><p>'+e(t(sub))+'</p></div>'+action+'</div>';}
function hero(creator=false){return '<section class="hero"><div><span class="eyebrow">'+e(t('introLabel'))+'</span><h1>'+e(t(creator?'creatorWelcome':'welcome'))+'</h1><p>'+e(t(creator?'creatorSubtitle':'subtitle'))+'</p><div class="hero-actions">'+(creator?'<button class="btn sun" data-action="scroll-work">'+e(t('myWork'))+icon('arrow')+'</button>':'<button class="btn sun" data-action="newMission">'+icon('plus')+e(t('newMission'))+'</button><button class="btn secondary" data-action="mode" data-view="creator">'+e(t('previewPortal'))+'</button>')+'</div><p class="hero-note">'+e(t('dataOnly'))+'</p></div><div class="hero-art" aria-hidden="true"><div class="sun-disc"></div><div class="cube"></div><div class="cube two"></div><div class="hero-tag">POP. DROP. CREATE.</div><div class="hero-caption">FRESH IDEAS. REAL CREATORS.</div></div></section>';}
function currenciesMetric(key){return ['IL','US'].filter(forMarket).map(m=>'<div class="kpi-currency">'+fm(C.stats(state,m)[key],C.currency(m))+'</div>').join('');}
function dashboardPage(){
 const cs=state.creators.filter(c=>forMarket(c.market)&&c.status==='active');const as=state.assignments.filter(a=>forMarket(getMission(a.missionId).market));
 const needs=[['nextApplicant','users',state.creators.filter(c=>c.status==='pending'&&forMarket(c.market)).length,'creators'],['nextReview','check',as.filter(a=>a.status==='submitted').length,'review'],['nextProof','globe',as.filter(a=>a.status==='published').length,'review'],['nextOffer','clock',as.filter(a=>a.status==='offered').length,'missions']];
 return hero()+ '<div class="toolbar">'+marketTabs()+'</div><div class="kpis"><div class="card"><div class="kpi-label">'+e(t('activeCreators'))+icon('users')+'</div><div class="kpi-value">'+cs.length+'</div><div class="kpi-meta">'+e(t('demoData'))+'</div></div><div class="card"><div class="kpi-label">'+e(t('pendingReviews'))+icon('check')+'</div><div class="kpi-value">'+as.filter(a=>a.status==='submitted').length+'</div><div class="kpi-meta">'+e(t('brandSafe'))+'</div></div><div class="card"><div class="kpi-label">'+e(t('commitments'))+icon('wallet')+'</div>'+currenciesMetric('committed')+'<div class="kpi-meta">'+e(t('costScope'))+'</div></div><div class="card"><div class="kpi-label">'+e(t('availableBudget'))+icon('brief')+'</div>'+currenciesMetric('available')+'<div class="kpi-meta">'+e(t('costScope'))+'</div></div></div><div class="split"><section class="card"><div class="section-head"><h2>'+e(t('nextActions'))+'</h2><span class="pill">'+e(t('forReview'))+'</span></div>'+needs.map(([label,i,n,p])=>'<div class="action-row"><div class="row-start"><span class="action-icon">'+icon(i)+'</span><span>'+e(t(label))+'</span></div><div class="row-start"><strong>'+n+'</strong><button class="btn ghost sm" data-action="nav" data-page="'+p+'" aria-label="'+e(t(label))+'">'+icon('arrow')+'</button></div></div>').join('')+'</section><section class="card"><h2>'+e(t('journey'))+'</h2><p class="small muted">'+e(t('journeySub'))+'</p><div class="journey">'+['application','offer','creation','approval','publication','payment'].map((s,i)=>'<div class="journey-step"><div class="step-number">'+(i+1)+'</div>'+e(t(s))+'</div>').join('')+'</div><div class="mini-info warning" style="margin-top:25px">'+e(t('budgetNote'))+'</div></section></div><section><div class="section-head"><h2>'+e(t('missions'))+'</h2>'+btn('viewAll','nav','data-page="missions"','ghost sm')+'</div><div class="mission-grid">'+state.missions.filter(m=>forMarket(m.market)).slice(0,2).map(missionCard).join('')+'</div></section><section class="split section-spacer"><div class="card"><h2>'+e(t('activity'))+'</h2>'+state.activity.slice(0,5).map(log=>'<div class="log-row"><span class="log-dot"></span><div>'+e(actionLabel(log.action))+'<div class="tiny muted">'+e(log.subject)+'</div></div><span class="log-time">'+date(log.at)+'</span></div>').join('')+'<p class="tiny muted" style="margin:12px 0 0">'+e(t('auditDemo'))+'</p></div><div class="card step-list"><span class="eyebrow">'+e(t('startHere'))+'</span><h2>'+e(t('howTo'))+'</h2><p>'+e(t('demoStep1'))+'</p><p>'+e(t('demoStep2'))+'</p><p>'+e(t('demoStep3'))+'</p></div></section>';
}
function missionCard(m){
 const used=C.allocation(state,m.id),count=C.missionCount(state,m.id),cur=C.currency(m.market),pct=Math.min(100,used/m.budget*100);
 const open=count<m.capacity&&m.deadline>=C.today();
 const adminBudget='<div class="mission-meta"><span>'+e(t('used'))+'</span><span>'+fm(used,cur)+' / '+fm(m.budget,cur)+'</span></div><div class="progress" role="meter" aria-label="'+e(t('used'))+'" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+pct.toFixed(1)+'"><span style="width:'+pct+'%"></span></div>';
 const creatorInfo='<p class="small muted">'+e(t('personalOffer'))+'</p>';
 return '<article class="card mission-card"><div class="mission-top '+(m.market==='IL'?'yellow':'')+'"><div><span class="eyebrow" style="font-size:9px;margin-bottom:6px">'+e(marketName(m.market))+' / '+cur+'</span><span class="small">'+e(t(m.objective))+'</span></div><div class="mission-art">'+icon(m.objective==='retail'?'bag':m.type==='blog'?'book':'video')+'</div></div><div class="mission-body"><h3>'+e(title(m))+'</h3><p class="small muted" style="margin:0">'+e(t('due'))+' '+date(m.deadline)+'</p><div class="mission-tags"><span class="pill outline">'+e(t(m.type))+'</span><span class="pill outline">'+count+' / '+m.capacity+' '+e(t('assigned'))+'</span><span class="pill">'+e(t(open?'available':'closed'))+'</span></div>'+(view==='creator'?creatorInfo:adminBudget)+'<div class="mission-footer"><span class="small muted">'+(view==='creator'?e(t('openPlaces'))+' '+(m.capacity-count):e(t('remaining'))+' '+fm(m.budget-used,cur))+'</span><button class="btn secondary sm" data-action="missionDetail" data-id="'+e(m.id)+'">'+e(t('brief'))+icon('arrow')+'</button></div></div></article>';
}
function missionsPage(){const ms=state.missions.filter(m=>forMarket(m.market));return pageTitle('missions','missionsIntro','<button class="btn sun" data-action="newMission">'+icon('plus')+e(t('newMission'))+'</button>')+'<div class="toolbar">'+marketTabs()+'</div>'+(ms.length?'<div class="mission-grid">'+ms.map(missionCard).join('')+'</div>':empty());}
function creatorsTable(){const cs=state.creators.filter(c=>forMarket(c.market)&&(!search||(c.name+' '+c.niche).toLowerCase().includes(search.toLowerCase())));return cs.length?'<div class="table-wrap"><table><thead><tr>'+['name','market','audience','engagement','fit','status'].map(k=>'<th scope="col">'+e(t(k))+'</th>').join('')+'</tr></thead><tbody>'+cs.map(c=>'<tr><td><div class="creator-cell">'+avatar(c)+'<div><button class="name-btn" data-action="creatorDetail" data-id="'+e(c.id)+'">'+e(c.name)+'</button><div class="tiny muted">'+e(c.platform)+' / '+e(c.niche)+'</div></div></div></td><td>'+e(marketName(c.market))+'</td><td><bdi>'+number(c.audience)+'</bdi><div class="tiny muted">'+e(t(['Blog','Newsletter'].includes(c.platform)?'monthlyReaders':'followers'))+'</div></td><td><bdi>'+c.engagement+'%</bdi></td><td><bdi>'+c.fit+'%</bdi></td><td>'+statusPill(c.status)+'<div class="tiny muted" style="margin-top:5px">'+e(t(c.metricsVerified?'metricsVerified':'metricsUnverified'))+'</div></td></tr>').join('')+'</tbody></table></div>':empty();}
function creatorsPage(){return pageTitle('creators','creatorIntro',btn('signup','apply','','sun'))+'<div class="toolbar">'+marketTabs()+'<div class="search"><label class="screen-reader-only" for="creator-search">'+e(t('search'))+'</label><input id="creator-search" type="search" placeholder="'+e(t('search'))+'" value="'+e(search)+'"></div></div><p class="small muted">'+e(t('tableHint'))+'</p><div id="creator-table">'+creatorsTable()+'</div>';}
function creatorDetail(id){const c=getCreator(id);if(!c)return;openModal(t('detailsFor'),'<div class="creator-cell"><span class="avatar large '+(c.market==='IL'?'gold':'')+'">'+e(initials(c.name))+'</span><div><h2>'+e(c.name)+'</h2><span class="small muted">'+e(c.platform)+' / '+e(marketName(c.market))+'</span></div></div><div class="details-grid"><div class="detail-tile"><span class="muted">'+e(t(['Blog','Newsletter'].includes(c.platform)?'monthlyReaders':'followers'))+'</span><strong>'+number(c.audience)+'</strong></div><div class="detail-tile"><span class="muted">'+e(t(['Blog','Newsletter'].includes(c.platform)?'clickRate':'engagement'))+'</span><strong>'+c.engagement+'%</strong></div><div class="detail-tile"><span class="muted">'+e(t('fit'))+'</span><strong>'+c.fit+'%</strong></div></div><div class="small"><strong>'+e(t('niche'))+'</strong>: '+e(c.niche)+'<br><strong>'+e(t('email'))+'</strong>: <bdi>'+e(c.email)+'</bdi></div><div class="link-row">'+link(c.url,'portfolio')+'</div>'+statusPill(c.status)+'<div class="mini-info '+(!c.metricsVerified?'warning':'')+'">'+e(t(c.metricsVerified?'metricsVerified':'metricsUnverified'))+'<div class="tiny" style="margin-top:6px">'+e(t('manualOnly'))+'</div></div><div class="modal-actions">'+(c.status==='pending'?btn('approveCreator','approveCreator','data-id="'+e(id)+'"','sun'):'')+(!c.metricsVerified?btn('verifyMetrics','verifyMetrics','data-id="'+e(id)+'"','secondary'):'')+'</div>');}
function missionDetail(id){
 const m=getMission(id);if(!m)return;
 const as=state.assignments.filter(a=>a.missionId===id&&(view!=='creator'||a.creatorId===creatorId)),cur=C.currency(m.market);
 const adminDetails='<div class="details-grid"><div class="detail-tile"><span class="muted">'+e(t('targetBudget'))+'</span><strong>'+fm(m.budget,cur)+'</strong></div><div class="detail-tile"><span class="muted">'+e(t('remaining'))+'</span><strong>'+fm(m.budget-C.allocation(state,id),cur)+'</strong></div><div class="detail-tile"><span class="muted">'+e(t('assigned'))+'</span><strong>'+C.missionCount(state,id)+' / '+m.capacity+'</strong></div></div>';
 openModal(title(m),'<div class="mission-detail-top"><div class="pill-row"><span class="pill">'+e(marketName(m.market))+'</span><span class="pill outline">'+e(t(m.type))+'</span><span class="pill outline">'+e(t(m.objective))+'</span></div><span class="small muted">'+date(m.deadline)+'</span></div>'+(view==='creator'?'<div class="mini-info" style="margin-bottom:20px">'+e(t('personalOffer'))+'</div>':adminDetails)+'<h3>'+e(t('briefDetail'))+'</h3><p class="brief-text">'+e(brief(m))+'</p><h3>'+e(t('cta'))+'</h3><p class="small">'+e(m.cta)+'</p><div class="mini-info">'+e(t('brandRules'))+'</div><div class="mini-info warning">'+e(t('rightsNote'))+'</div>'+(as.length?'<hr class="hr"><h3>'+e(t('assigned'))+'</h3>'+as.map(a=>'<div class="action-row"><div>'+e(getCreator(a.creatorId).name)+'<div style="margin-top:5px">'+statusPill(a.status)+'</div></div>'+btn('open','work','data-id="'+e(a.id)+'"','secondary sm')+'</div>').join(''):'')+(view==='admin'?'<div class="modal-actions">'+btn('offerCreator','offer','data-id="'+e(id)+'"','sun')+'</div><p class="tiny muted" style="margin-top:14px">'+e(t('costsNotIncluded'))+'</p>':''),true);
}
function newMission(){const def=market==='US'?'US':'IL';openModal(t('newMission'),'<form id="mission-form"><div class="form-grid">'+field('title','title','','text','required maxlength="150" placeholder="'+e(t('missionTitlePlaceholder'))+'"')+select('market','market',[['IL',marketName('IL')],['US',marketName('US')]],def)+select('type','type',['reel','story','blog'].map(k=>[k,t(k)]),'reel')+select('objective','objective',['dtc','retail','education'].map(k=>[k,t(k)]),'education')+field('targetBudget','budget',def==='IL'?2500:1000,'number','min="1" max="10000000" step="0.01" required')+field('capacity','capacity',5,'number','min="1" max="500" step="1" required')+field('deadline','deadline',C.future(21),'date','min="'+C.today()+'" required')+field('cta','cta','','text','required maxlength="300"')+'<div class="field full"><label for="brief">'+e(t('instructions'))+'</label><textarea id="brief" name="brief" required maxlength="5000">'+e(t('briefDefault'))+'</textarea><div class="hint">'+e(t('briefBuilderNote'))+'</div></div></div><div class="mini-info warning">'+e(t('priceDisclaimer'))+'<br>'+e(t('currencyFixed'))+'</div><div class="modal-actions">'+btn('briefBuilder','buildBrief','','secondary')+'<button type="submit" class="btn sun">'+e(t('create'))+'</button></div></form>',true);}
function offerMission(id){const m=getMission(id);if(!m)return;const cs=state.creators.filter(c=>c.status==='active'&&c.market===m.market&&!state.assignments.some(a=>a.missionId===id&&a.creatorId===c.id&&a.status!=='cancelled'));if(!cs.length){toast(t('noEligible'),true);return;}
openModal(t('offerCreator'),'<form id="offer-form" data-mission="'+e(id)+'"><h3>'+e(title(m))+'</h3><div class="small muted">'+e(t('remaining'))+' '+fm(m.budget-C.allocation(state,id),C.currency(m.market))+'</div><hr class="hr">'+select('chooseCreator','creatorId',cs.map(c=>[c.id,c.name]),cs[0].id)+'<div id="quote-meta"></div><div class="offer-breakdown">'+field('productionFee','production',0,'number','min="0" max="10000000" step="0.01" required')+field('distributionFee','distribution',0,'number','min="0" max="10000000" step="0.01" required')+field('rightsFee','rights',0,'number','min="0" max="10000000" step="0.01" required')+'</div><div class="total-box"><span>'+e(t('total'))+'</span><strong id="quote-total"></strong></div><div class="form-grid" style="margin-top:16px">'+field('commission','commission',0,'number','min="0" max="100" step="0.1"')+'</div><p class="small muted" style="margin-top:10px">'+e(t('commissionNote'))+'</p><div class="mini-info">'+e(t('rightsNote'))+'</div><div class="mini-info warning">'+e(t('priceDisclaimer'))+'</div><div class="modal-actions"><button class="btn sun" type="submit">'+e(t('reserve'))+'</button></div><p class="tiny muted" style="margin-top:12px">'+e(t('noEmail'))+'</p></form>');updateQuote();}
function updateQuote(){const f=$('#offer-form');if(!f)return;const q=C.quote(state,f.elements.creatorId.value,f.dataset.mission),c=getCreator(f.elements.creatorId.value);['production','distribution','rights'].forEach(k=>f.elements[k].value=q[k]);$('#quote-meta').innerHTML='<div class="quote-summary">'+e(t('quoteBasedOn'))+'<br><bdi>'+number(c.audience)+'</bdi> / '+e(t('engagement'))+' <bdi>'+c.engagement+'%</bdi> / '+e(t('fit'))+' <bdi>'+c.fit+'%</bdi></div>'+(!c.metricsVerified?'<div class="mini-info warning">'+e(t('unverifiedBlocked'))+'</div>':'')+(q.manual?'<div class="mini-info warning">'+e(t('blogManual'))+'</div>':'');updateTotal();}
function updateTotal(){const f=$('#offer-form');if(!f)return;const n=['production','distribution','rights'].reduce((s,k)=>s+(Number(f.elements[k].value)||0),0);$('#quote-total').textContent=money(n,C.currency(getMission(f.dataset.mission).market));}
function reviewPage(){const as=state.assignments.filter(a=>['submitted','published','changes','approved'].includes(a.status)&&forMarket(getMission(a.missionId).market));return pageTitle('review','reviewIntro')+'<div class="toolbar">'+marketTabs()+'</div>'+(as.length?'<div class="content-list">'+as.map(a=>{const m=getMission(a.missionId),c=getCreator(a.creatorId);return '<article class="card review-card"><div class="creator-cell">'+avatar(c)+'<div><span class="small muted">'+e(c.name)+'</span><h3>'+e(title(m))+'</h3><div class="pill-row">'+statusPill(a.status)+'<span class="pill outline">'+e(marketName(m.market))+'</span></div></div></div><div class="review-actions"><strong>'+fm(a.fees.total,a.fees.currency)+'</strong>'+btn(a.status==='published'?'proofReview':'open','work','data-id="'+e(a.id)+'"','sun sm')+'</div></article>';}).join('')+'</div>':empty());}
function feesSummary(a){return '<div class="offer-breakdown">'+['production','distribution','rights'].map((k,i)=>'<div class="detail-tile"><span class="muted">'+e(t(['productionFee','distributionFee','rightsFee'][i]))+'</span><strong style="font-size:17px">'+fm(a.fees[k],a.fees.currency)+'</strong></div>').join('')+'</div><div class="total-box"><span>'+e(t('total'))+'</span><strong>'+fm(a.fees.total,a.fees.currency)+'</strong></div><p class="tiny muted" style="margin:9px 0 0">'+e(t('offerLocked'))+'</p>'+(a.commission>0?'<div class="mini-info warning">'+e(t('commission'))+': '+a.commission+'%<br>'+e(t('commissionNote'))+'</div>':'');}
function workModal(id){const a=state.assignments.find(x=>x.id===id);if(!a)return;const m=getMission(a.missionId),c=getCreator(a.creatorId);let html='<div class="row-start" style="justify-content:space-between"><div><h3>'+e(title(m))+'</h3><p class="small muted">'+e(c.name)+'</p></div>'+statusPill(a.status)+'</div>'+feesSummary(a)+'<hr class="hr"><h3>'+e(t('brief'))+'</h3><p class="brief-text">'+e(brief(m))+'</p><div class="mini-info">'+e(t('rightsNote'))+'</div>';
if(a.feedback)html+='<div class="mini-info warning"><strong>'+e(t('feedback'))+'</strong><p style="margin:7px 0 0;white-space:pre-wrap">'+e(a.feedback)+'</p></div>';
if(a.contentUrl)html+='<div class="link-row">'+link(a.contentUrl,'openContent')+(a.publicationUrl?link(a.publicationUrl,'openPublication'):'')+'</div>';
if(a.notes)html+='<p class="small muted" style="white-space:pre-wrap">'+e(a.notes)+'</p>';
if(view==='creator'){
 if(a.creatorId!==creatorId)return;
 if(a.status==='offered')html+='<hr class="hr"><form id="accept-form" data-id="'+e(id)+'">'+checkbox('confirmed','acceptTerms')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('acceptOffer'))+'</button>'+btn('decline','decline','data-id="'+e(id)+'"','secondary')+'</div></form>';
 if(['accepted','changes'].includes(a.status))html+='<hr class="hr"><form id="content-form" data-id="'+e(id)+'">'+field('contentUrl','url',a.contentUrl,'url','required placeholder="https://example.com/preview"')+'<p class="small muted" style="margin-top:7px">'+e(t('contentHelp'))+'</p><div class="field"><label for="content-notes">'+e(t('notes'))+'</label><textarea id="content-notes" name="notes" maxlength="2000">'+e(a.notes)+'</textarea></div><div class="modal-actions"><button type="submit" class="btn sun">'+e(t('sendReview'))+'</button></div></form>';
 if(a.status==='approved')html+='<hr class="hr"><form id="publication-form" data-id="'+e(id)+'">'+field('publicationUrl','url','','url','required placeholder="https://example.com/published-post"')+'<p class="small muted" style="margin-top:8px">'+e(t('publicationHelp'))+'</p><div class="modal-actions"><button type="submit" class="btn sun">'+e(t('savePublication'))+'</button></div></form>';
}else{
 if(a.status==='submitted')html+='<hr class="hr"><form id="review-form" data-id="'+e(id)+'"><h3>'+e(t('checks'))+'</h3>'+['checkProduct','checkClaims','checkRights','checkDisclosure'].map((k,i)=>checkbox('check'+i,k)).join('')+'<div class="field" style="margin-top:16px"><label for="feedback">'+e(t('feedback'))+'</label><textarea name="feedback" id="feedback" maxlength="2000"></textarea></div><div class="modal-actions"><button class="btn sun" type="submit" name="decision" value="approved">'+e(t('approveContent'))+'</button><button class="btn secondary" type="submit" name="decision" value="changes">'+e(t('requestChanges'))+'</button></div></form>';
 if(a.status==='published')html+='<hr class="hr"><form id="verify-form" data-id="'+e(id)+'">'+checkbox('confirmed','verifyPublicationText')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('verifyPublication'))+'</button></div></form>';
 if(a.status==='payable')html+='<hr class="hr"><form id="payment-form" data-id="'+e(id)+'">'+field('reference','reference','','text','required minlength="3" maxlength="100" placeholder="'+e(t('demoReference'))+'"')+checkbox('confirmed','paymentConfirm')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('recordPayment'))+'</button></div></form>';
 if(['offered','accepted','submitted','changes','approved'].includes(a.status))html+='<div class="modal-actions">'+btn('cancelWork','cancelWork','data-id="'+e(id)+'"','danger sm')+'</div>';
}
if(a.status==='paid')html+='<div class="mini-info"><strong>'+e(t('manualRecorded'))+'</strong><br>'+e(a.payment.reference)+' / '+date(a.payment.at)+'</div>';
html+='<p class="tiny muted" style="margin-top:18px">'+e(t('noMoney'))+' / '+e(t('noFileUpload'))+'</p>';openModal(t('workDetail'),html,true);}
function paymentsPage(){const as=state.assignments.filter(a=>['payable','paid'].includes(a.status)&&forMarket(getMission(a.missionId).market));const table=as.length?'<div class="table-wrap"><table><thead><tr>'+['name','title','amount','status','actions'].map(k=>'<th>'+e(t(k))+'</th>').join('')+'</tr></thead><tbody>'+as.map(a=>'<tr><td>'+e(getCreator(a.creatorId).name)+'</td><td>'+e(title(getMission(a.missionId)))+'</td><td>'+fm(a.fees.total,a.fees.currency)+'</td><td>'+statusPill(a.status)+'</td><td>'+btn(a.status==='payable'?'recordPayment':'details','work','data-id="'+e(a.id)+'"','secondary sm')+'</td></tr>').join('')+'</tbody></table></div>':empty();return pageTitle('payments','payoutIntro',btn('exportCsv','exportCsv','','secondary'))+'<div class="toolbar">'+marketTabs()+'</div><div class="kpis"><div class="card"><div class="kpi-label">'+e(t('readyToPay'))+'</div>'+currenciesMetric('payable')+'</div><div class="card"><div class="kpi-label">'+e(t('recordedPayments'))+'</div>'+currenciesMetric('recorded')+'</div><div class="card"><div class="kpi-label">'+e(t('commitments'))+'</div>'+currenciesMetric('committed')+'</div><div class="card"><div class="kpi-label">'+e(t('noMoney'))+'</div><div class="kpi-value">'+icon('shield')+'</div><div class="kpi-meta">'+e(t('manualRecorded'))+'</div></div></div>'+table+'<div class="mini-info warning">'+e(t('costsNotIncluded'))+'<br>'+e(t('commissionDisabled'))+'</div>';}
function creatorPage(){const eligible=state.creators.filter(c=>c.status==='active');if(!eligible.some(c=>c.id===creatorId))creatorId=eligible[0]?.id||'';const c=getCreator(creatorId);if(!c)return '<p>'+e(t('creatorUnavailable'))+'</p>';const as=state.assignments.filter(a=>a.creatorId===creatorId&&a.status!=='cancelled');const total=as.filter(a=>a.status!=='paid').reduce((sum,a)=>sum+a.fees.total,0);const recorded=as.filter(a=>a.status==='paid').reduce((sum,a)=>sum+a.fees.total,0);return '<div class="creator-layout"><div class="toolbar"><div class="creator-picker"><label for="creator-picker" class="screen-reader-only">'+e(t('creator'))+'</label><select id="creator-picker">'+eligible.map(x=>'<option value="'+e(x.id)+'" '+(x.id===creatorId?'selected':'')+'>'+e(x.name)+'</option>').join('')+'</select></div><span class="small muted">'+e(t('demoIdentity'))+'</span></div>'+hero(true)+'<div class="kpis"><div class="card"><div class="kpi-label">'+e(t('offers'))+'</div><div class="kpi-value">'+as.filter(a=>a.status==='offered').length+'</div></div><div class="card"><div class="kpi-label">'+e(t('myWork'))+'</div><div class="kpi-value">'+as.length+'</div></div><div class="card"><div class="kpi-label">'+e(t('commitments'))+'</div><div class="kpi-currency">'+fm(total,C.currency(c.market))+'</div></div><div class="card"><div class="kpi-label">'+e(t('recorded'))+'</div><div class="kpi-currency">'+fm(recorded,C.currency(c.market))+'</div></div></div><section id="my-work"><div class="section-head"><h2>'+e(t('myWork'))+'</h2><span class="pill">'+e(marketName(c.market))+'</span></div>'+(as.length?'<div class="work-grid">'+as.map(a=>{const m=getMission(a.missionId);return '<article class="card work-card">'+statusPill(a.status)+'<h3>'+e(title(m))+'</h3><div class="small muted">'+e(t(m.type))+' / '+date(m.deadline)+'</div><div class="fee">'+fm(a.fees.total,a.fees.currency)+'</div><p class="tiny muted">'+e(t('offerLocked'))+'</p>'+btn(a.status==='offered'?'offer':a.status==='accepted'||a.status==='changes'?'submitContent':a.status==='approved'?'reportPublication':'details','work','data-id="'+e(a.id)+'"','sun wide')+'</article>';}).join('')+'</div>':empty())+'</section><section class="section-spacer"><h2>'+e(t('availableMissions'))+'</h2><div class="mission-grid">'+state.missions.filter(m=>m.market===c.market&&C.missionCount(state,m.id)<m.capacity&&m.deadline>=C.today()).map(missionCard).join('')+'</div></section><div class="mini-info">'+e(t('creatorBrandRules'))+'</div></div>';}
function settingsPage(){return pageTitle('settings','ratesIntro')+'<div class="setting-grid"><div class="card"><h2>'+e(t('storage'))+'</h2><p class="small muted">'+e(t('storageDesc'))+'</p><div class="modal-actions">'+btn('export','export','','secondary')+btn('import','import','','secondary')+btn('reset','reset','','danger')+'</div><input type="file" id="import-file" accept="application/json,.json" hidden><div class="mini-info warning">'+e(t('dataOnly'))+'</div></div><div class="card"><h2>'+e(t('connections'))+'</h2>'+['ai','social','payouts','commerce'].map(k=>'<div class="connection"><span>'+e(t(k))+'</span><span class="pill outline">'+e(t('notConnected'))+'</span></div>').join('')+'</div></div><section class="card section-spacer"><h2>'+e(t('formula'))+'</h2><p class="small">'+e(t('formulaText'))+'</p><p class="small muted">'+e(t('multipliers'))+'</p><div class="mini-info warning">'+e(t('priceDisclaimer'))+'</div></section><form id="rates-form" class="section-spacer"><div class="setting-grid">'+['IL','US'].map(m=>'<section class="card"><h2>'+e(marketName(m))+' / '+C.currency(m)+'</h2><div class="table-wrap"><table class="rates-table"><thead><tr><th>'+e(t('type'))+'</th><th>'+e(t('productionFee'))+'</th></tr></thead><tbody>'+['reel','story','blog'].map(k=>'<tr><td><label for="rate-'+m+'-'+k+'">'+e(t(k))+'</label></td><td><input id="rate-'+m+'-'+k+'" name="'+m+'-p-'+k+'" value="'+state.rates[m].production[k]+'" type="number" min="0" max="10000000" step="0.01" required></td></tr>').join('')+'</tbody></table></div><h3 style="margin-top:22px">'+e(t('tiers'))+'</h3><div class="table-wrap"><table class="rates-table"><tbody>'+state.rates[m].distribution.map((v,i)=>'<tr><td><label for="tier-'+m+'-'+i+'">'+e(t('tier'+(i+1)))+'</label></td><td><input id="tier-'+m+'-'+i+'" name="'+m+'-d-'+i+'" value="'+v+'" type="number" min="0" max="10000000" step="0.01" required></td></tr>').join('')+'</tbody></table></div></section>').join('')+'</div><div class="modal-actions"><button class="btn sun" type="submit">'+e(t('saveRates'))+'</button><span class="small muted">v'+state.ratesVersion+'</span></div></form>';}
function renderApply(){document.documentElement.dir=lang==='he'?'rtl':'ltr';$('#app').innerHTML='<div class="content onboarding"><header class="onboarding-header"><div class="brandmark">Simplii<span>Good</span></div><div class="brand-sub" style="margin:12px 0 20px">CREATOR CLUB</div><button class="lang-btn" data-action="lang">'+(lang==='he'?'EN':'HE')+'</button></header><div class="demo-banner">'+e(t('publicDemo'))+'</div><div class="page-title"><div><h1>'+e(t('signupTitle'))+'</h1><p>'+e(t('signupSub'))+'</p></div></div><section class="card"><form id="apply-form"><div class="form-grid">'+field('displayName','name','','text','required maxlength="120" autocomplete="off"')+field('email','email','','email','required maxlength="254" placeholder="creator@example.test" autocomplete="off"')+select('market','market',[['IL',marketName('IL')],['US',marketName('US')]],'IL')+select('platform','platform',['Instagram','TikTok','Blog','Newsletter','YouTube'].map(k=>[k,k]),'Instagram')+field('audienceLabel','audience','','number','required min="0" max="1000000000" step="1"')+field('engagementLabel','engagement','','number','required min="0" max="100" step="0.1"')+field('fitLabel','fit','','number','required min="0" max="100" step="0.1"')+field('niche','niche','','text','required maxlength="300"')+'<div class="field full"><label for="profile-url">'+e(t('profileUrl'))+'</label><input id="profile-url" name="url" type="url" required placeholder="https://example.com/profile" maxlength="2000"></div></div><div class="mini-info warning">'+e(t('noteMetrics'))+'</div>'+checkbox('consent','consent')+'<div id="application-errors" role="alert" class="inline-error hide"></div><div class="modal-actions"><button type="submit" class="btn sun">'+e(t('apply'))+'</button>'+btn('backAdmin','mode','data-view="admin"','secondary')+'</div></form></section></div>';}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function csvCell(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function exportCsv(){const rows=[['DEMO ONLY - NO MONEY TRANSFERRED'],['assignment_id','creator','market','mission','creation_fee','publication_fee','rights_fee','total','currency','status','reference','recorded_at']];state.assignments.filter(a=>['payable','paid'].includes(a.status)&&forMarket(getMission(a.missionId).market)).forEach(a=>{const m=getMission(a.missionId);rows.push([a.id,getCreator(a.creatorId).name,m.market,title(m),a.fees.production,a.fees.distribution,a.fees.rights,a.fees.total,a.fees.currency,a.status,a.payment?.reference||'',a.payment?.at||'']);});download('simpliigood-demo-payments-'+C.today()+'.csv','\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
const data=f=>Object.fromEntries(new FormData(f).entries());
document.addEventListener('click',event=>{
 const target=event.target.closest('[data-action]');if(!target)return;const a=target.dataset.action,id=target.dataset.id;
 if(a==='close')closeModal();
 else if(a==='menu')$('#sidebar')?.classList.toggle('open');
 else if(a==='lang'){lang=lang==='he'?'en':'he';closeModal();render();}
 else if(a==='nav'){view='admin';page=target.dataset.page;closeModal();render();window.scrollTo(0,0);}
 else if(a==='mode'){view=target.dataset.view;closeModal();render();window.scrollTo(0,0);}
 else if(a==='market'){market=target.dataset.market;render();}
 else if(a==='newMission')newMission();
 else if(a==='missionDetail')missionDetail(id);
 else if(a==='creatorDetail')creatorDetail(id);
 else if(a==='approveCreator')act('creator.approve',{id});
 else if(a==='verifyMetrics'){if(confirm(t('manualOnly')+'\n\n'+t('verifyMetrics')+'?'))act('creator.verify',{id,confirmed:true});}
 else if(a==='offer')offerMission(id);
 else if(a==='work')workModal(id);
 else if(a==='apply'){view='apply';closeModal();render();window.scrollTo(0,0);}
 else if(a==='buildBrief'){const f=$('#mission-form'),l=f.elements.market.value==='US'?'en':'he';f.elements.brief.value=TRANSLATIONS[l].briefDefault;toast(t('briefGenerated'));}
 else if(a==='scroll-work')$('#my-work')?.scrollIntoView({behavior:'smooth',block:'start'});
 else if(a==='cancelWork'){if(confirm(t('cancelConfirm'))){const reason=prompt(t('cancelReason'),'Demo cancellation');if(reason)act('assignment.cancel',{id,reason});}}
 else if(a==='decline'){if(confirm(t('declineConfirm')))act('assignment.decline',{id});}
 else if(a==='export'){download('simpliigood-creator-club-backup-'+C.today()+'.json',safeJSON(state),'application/json');toast(t('exported'));}
 else if(a==='exportCsv')exportCsv();
 else if(a==='import')$('#import-file')?.click();
 else if(a==='reset'){if(confirm(t('resetConfirm'))){persist(C.createSeed());market='all';creatorId='c3';render();toast(t('saved'));}}
});
document.addEventListener('input',event=>{if(event.target.id==='creator-search'){search=event.target.value;$('#creator-table').innerHTML=creatorsTable();}if(event.target.closest('#offer-form')&&['production','distribution','rights'].includes(event.target.name))updateTotal();});
document.addEventListener('change',async event=>{
 if(event.target.id==='creator-picker'){creatorId=event.target.value;render();}
 if(event.target.closest('#offer-form')&&event.target.name==='creatorId')updateQuote();
 if(event.target.id==='import-file'){
  const file=event.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error();const next=JSON.parse(await file.text());C.validateState(next);if(confirm(t('importConfirm'))){persist(next);render();toast(t('imported'));}}catch(_){toast(t('invalidBackup'),true);}finally{event.target.value='';}
 }
});
document.addEventListener('submit',event=>{
 const f=event.target;if(!(f instanceof HTMLFormElement))return;event.preventDefault();const p=data(f),id=f.dataset.id;
 if(f.id==='mission-form')act('mission.create',p);
 else if(f.id==='offer-form')act('assignment.offer',{...p,missionId:f.dataset.mission});
 else if(f.id==='accept-form')act('assignment.accept',{id,confirmed:f.elements.confirmed.checked});
 else if(f.id==='content-form')act('assignment.submit',{id,...p});
 else if(f.id==='publication-form')act('assignment.publish',{id,url:p.url});
 else if(f.id==='review-form')act('assignment.review',{id,decision:event.submitter?.value,feedback:p.feedback,checks:[0,1,2,3].map(i=>f.elements['check'+i].checked)});
 else if(f.id==='verify-form')act('assignment.verify',{id,confirmed:f.elements.confirmed.checked});
 else if(f.id==='payment-form')act('assignment.record',{id,reference:p.reference,confirmed:f.elements.confirmed.checked});
 else if(f.id==='rates-form'){const rates={};['IL','US'].forEach(m=>{rates[m]={production:{},distribution:[0,1,2,3,4].map(i=>p[m+'-d-'+i])};['reel','story','blog'].forEach(k=>rates[m].production[k]=p[m+'-p-'+k]);});act('settings.rates',{rates});}
 else if(f.id==='apply-form'){
  try{const next=C.dispatch(state,'creator.apply',{...p,consent:f.elements.consent.checked},{role:'public'});persist(next);view='admin';page='creators';market='all';render();toast(t('applicationSaved'));}catch(err){$('#application-errors').textContent=t(err.message);$('#application-errors').classList.remove('hide');}
 }
});
document.addEventListener('keydown',event=>{
 const modal=$('#modal-root .modal');if(!modal)return;if(event.key==='Escape'){closeModal();return;}
 if(event.key==='Tab'){const els=[...modal.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')].filter(x=>x.offsetParent!==null),first=els[0],last=els.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}
});
window.addEventListener('storage',event=>{if(event.key!==KEY||!event.newValue)return;try{const next=JSON.parse(event.newValue);C.validateState(next);state=next;closeModal();render();toast(t('stale'));}catch(_){toast(t('invalidBackup'),true);}});
window.ClubDemo={getState:()=>JSON.parse(JSON.stringify(state)),core:C};
render();if(loadError)toast(t(loadError),true);
})();
