/* Application shell: sidebar, top bar, page routing, hero and KPI helpers. */
function render(){
 document.documentElement.lang=lang;document.documentElement.dir=lang==='he'?'rtl':'ltr';
 try{localStorage.setItem(PREF,JSON.stringify({lang}));}catch(_){}
 if(view==='apply'){renderApply();return;}
 const pending=state.assignments.filter(a=>['submitted','published'].includes(a.status)).length;
 const nav=[['dashboard','grid'],['creators','users'],['missions','brief'],['review','check'],['payments','wallet'],['settings','settings']];
 $('#app').innerHTML='<aside class="sidebar" id="sidebar"><div><div class="brandmark" aria-label="SimpliiGood">Simplii<span>Good</span></div><div class="brand-sub">CREATOR CLUB</div></div><div class="side-divider"></div><span class="eyebrow" style="color:#8eaca8;font-size:9px">'+e(t('pilot'))+'</span><nav aria-label="'+e(t('admin'))+'">'+nav.map(([p,i])=>'<button data-action="nav" data-page="'+p+'" class="nav-item '+(page===p&&view==='admin'?'active':'')+'">'+icon(i)+e(t(p))+(p==='review'&&pending?'<span class="nav-count">'+pending+'</span>':'')+'</button>').join('')+'</nav><div class="side-bottom"><div class="side-note"><span class="dot"></span> '+e(t('offline'))+'<div style="margin-top:10px;font-size:11px">'+e(t('brandSafe'))+'</div></div><button class="nav-item" data-action="apply">'+icon('users')+e(t('openApplication'))+'</button><div class="side-footer">'+e(t('fresh'))+'</div></div></aside><div class="app-shell"><header class="topbar"><div class="row-start"><button class="menu-toggle" data-action="menu" aria-label="'+e(t('mobileNav'))+'">'+icon('menu')+'</button><div class="top-title"><strong style="font-size:13px">'+e(t(view==='creator'?'creator':page))+'</strong><div class="tiny muted">SIMPLIIGOOD / CREATOR CLUB</div></div></div><div class="top-actions"><span class="demo-pill"><span class="dot"></span>'+e(t('demo'))+'</span><div class="mode-switch" aria-label="'+e(t('viewMode'))+'"><button data-action="mode" data-view="admin" class="'+(view==='admin'?'active':'')+'">'+e(t('admin'))+'</button><button data-action="mode" data-view="creator" class="'+(view==='creator'?'active':'')+'">'+e(t('creator'))+'</button></div><button class="lang-btn" data-action="lang" aria-label="Change language">'+(lang==='he'?'EN':'HE')+'</button></div></header><main class="content" id="main-content"><div class="demo-banner">'+icon('shield')+'<span>'+e(t('demoBanner'))+'</span></div>'+(view==='creator'?creatorPage():({dashboard:dashboardPage,creators:creatorsPage,missions:missionsPage,review:reviewPage,payments:paymentsPage,settings:settingsPage}[page]||dashboardPage)())+'<footer class="footer"><span class="ltr">'+e(t('footer'))+'</span><span>v'+APP_VERSION+' / '+e(t('savedLocally'))+'</span></footer></main></div>';
}
function pageTitle(key,sub,action=''){return '<div class="page-title"><div><h1>'+e(t(key))+'</h1><p>'+e(t(sub))+'</p></div>'+action+'</div>';}
function hero(creator=false){return '<section class="hero"><div><span class="eyebrow">'+e(t('introLabel'))+'</span><h1>'+e(t(creator?'creatorWelcome':'welcome'))+'</h1><p>'+e(t(creator?'creatorSubtitle':'subtitle'))+'</p><div class="hero-actions">'+(creator?'<button class="btn sun" data-action="scroll-work">'+e(t('myWork'))+icon('arrow')+'</button>':'<button class="btn sun" data-action="newMission">'+icon('plus')+e(t('newMission'))+'</button><button class="btn secondary" data-action="mode" data-view="creator">'+e(t('previewPortal'))+'</button>')+'</div><p class="hero-note">'+e(t('dataOnly'))+'</p></div><div class="hero-art" aria-hidden="true"><div class="sun-disc"></div><div class="cube"></div><div class="cube two"></div><div class="hero-tag">POP. DROP. CREATE.</div><div class="hero-caption">FRESH IDEAS. REAL CREATORS.</div></div></section>';}
function currenciesMetric(key){return ['IL','US'].filter(forMarket).map(m=>'<div class="kpi-currency">'+fm(C.stats(state,m)[key],C.currency(m))+'</div>').join('');}
