/* Content review: review list, fee summary and the work modal used by both roles. */
function reviewPage(){const as=state.assignments.filter(a=>['submitted','published','changes','approved'].includes(a.status)&&forMarket(getMission(a.missionId).market));return pageTitle('review','reviewIntro')+'<div class="toolbar">'+marketTabs()+'</div>'+(as.length?'<div class="content-list">'+as.map(a=>{const m=getMission(a.missionId),c=getCreator(a.creatorId);return '<article class="card review-card"><div class="creator-cell">'+avatar(c)+'<div><span class="small muted">'+e(c.name)+'</span><h3>'+e(title(m))+'</h3><div class="pill-row">'+statusPill(a.status)+'<span class="pill outline">'+e(marketName(m.market))+'</span></div></div></div><div class="review-actions"><strong>'+amountLabel(a)+'</strong>'+btn(a.status==='published'?'proofReview':'open','work','data-id="'+e(a.id)+'"','sun sm')+'</div></article>';}).join('')+'</div>':empty());}
function affiliateSummary(a){const x=a.affiliate;return '<div class="offer-breakdown"><div class="detail-tile"><span class="muted">'+e(t('creatorShare'))+'</span><strong style="font-size:17px">'+e(x.creatorShare)+'%</strong></div><div class="detail-tile"><span class="muted">'+e(t('audienceDiscount'))+'</span><strong style="font-size:17px">'+e(x.audienceDiscount)+'%</strong></div><div class="detail-tile"><span class="muted">'+e(t('promoCode'))+'</span><strong style="font-size:17px"><bdi>'+e(x.promoCode)+'</bdi></strong></div></div><div class="total-box"><span>'+e(t('productPackage'))+'</span><strong>'+e(x.productPackage)+'</strong></div><p class="tiny muted" style="margin:9px 0 0">'+e(t('noCashFee'))+' / '+e(t('offerLocked'))+'</p>'+(a.payment?'<div class="mini-info">'+e(t('reportedSales'))+': '+fm(a.payment.salesTotal||0,a.fees.currency)+' / '+e(t('commissionAmount'))+': '+fm(a.payment.amount||0,a.fees.currency)+'</div>':'');}
function feesSummary(a){if(a.deal==='affiliate')return affiliateSummary(a);return '<div class="offer-breakdown">'+['production','distribution','rights'].map((k,i)=>'<div class="detail-tile"><span class="muted">'+e(t(['productionFee','distributionFee','rightsFee'][i]))+'</span><strong style="font-size:17px">'+fm(a.fees[k],a.fees.currency)+'</strong></div>').join('')+'</div><div class="total-box"><span>'+e(t('total'))+'</span><strong>'+fm(a.fees.total,a.fees.currency)+'</strong></div><p class="tiny muted" style="margin:9px 0 0">'+e(t('offerLocked'))+'</p>'+(a.commission>0?'<div class="mini-info warning">'+e(t('commission'))+': '+a.commission+'%<br>'+e(t('commissionNote'))+'</div>':'');}
function workModal(id){const a=state.assignments.find(x=>x.id===id);if(!a)return;const m=getMission(a.missionId),c=getCreator(a.creatorId);let html='<div class="row-start" style="justify-content:space-between"><div><h3>'+e(title(m))+'</h3><p class="small muted">'+e(c.name)+'</p></div>'+statusPill(a.status)+'</div>'+feesSummary(a)+'<hr class="hr"><h3>'+e(t('brief'))+'</h3><p class="brief-text">'+e(brief(m))+'</p><div class="mini-info">'+e(t('rightsNote'))+'</div>';
if(a.feedback)html+='<div class="mini-info warning"><strong>'+e(t('feedback'))+'</strong><p style="margin:7px 0 0;white-space:pre-wrap">'+e(a.feedback)+'</p></div>';
if(a.contentUrl)html+='<div class="link-row">'+link(a.contentUrl,'openContent')+(a.publicationUrl?link(a.publicationUrl,'openPublication'):'')+'</div>';
if(a.notes)html+='<p class="small muted" style="white-space:pre-wrap">'+e(a.notes)+'</p>';
if(view==='creator'){
 if(a.creatorId!==creatorId)return;
 if(a.status==='offered')html+='<hr class="hr"><form id="accept-form" data-id="'+e(id)+'">'+checkbox('confirmed','acceptTerms')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('acceptOffer'))+'</button>'+btn('decline','decline','data-id="'+e(id)+'"','secondary')+'</div></form>';
 if(['accepted','changes'].includes(a.status))html+='<hr class="hr"><form id="content-form" data-id="'+e(id)+'">'+field('contentUrl','url',a.contentUrl,'url','required placeholder="https://example.com/preview"')+'<p class="small muted" style="margin-top:7px">'+e(t('contentHelp'))+'</p><div class="field"><label for="content-notes">'+e(t('notes'))+'</label><textarea id="content-notes" name="notes" maxlength="2000">'+e(a.notes)+'</textarea></div><div class="modal-actions"><button type="submit" class="btn sun">'+e(t('sendReview'))+'</button></div></form>';
 if(a.status==='approved')html+='<hr class="hr"><form id="publication-form" data-id="'+e(id)+'">'+field('publicationUrl','url','','url','required placeholder="https://example.com/published-post"')+'<p class="small muted" style="margin-top:8px">'+e(t('publicationHelp'))+'</p><div class="modal-actions"><button type="submit" class="btn sun">'+e(t('savePublication'))+'</button></div></form>';
}else{
 if(a.status==='submitted')html+='<hr class="hr"><form id="review-form" data-id="'+e(id)+'"><h3>'+e(t('checks'))+'</h3>'+['checkProduct','checkClaims','checkRights','checkDisclosure'].map((k,i)=>checkbox('check'+i,k)).join('')+'<div class="field" style="margin-top:16px"><label for="feedback">'+e(t('feedback'))+'</label><textarea name="feedback" id="feedback" maxlength="2000"></textarea></div><div class="modal-actions"><button class="btn sun" type="submit" name="decision" value="approved">'+e(t('approveContent'))+'</button><button class="btn secondary" type="submit" name="decision" value="changes">'+e(t('requestChanges'))+'</button></div></form>';
 if(a.status==='published')html+='<hr class="hr"><form id="verify-form" data-id="'+e(id)+'">'+checkbox('confirmed','verifyPublicationText')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('verifyPublication'))+'</button></div></form>';
 if(a.status==='payable')html+='<hr class="hr"><form id="payment-form" data-id="'+e(id)+'">'+(a.deal==='affiliate'?'<div class="mini-info">'+e(t('affiliateSettlement'))+'</div>'+field('salesTotal','salesTotal','','number','min="0" max="100000000" step="0.01" required'):'')+field('reference','reference','','text','required minlength="3" maxlength="100" placeholder="'+e(t('demoReference'))+'"')+checkbox('confirmed','paymentConfirm')+'<div class="modal-actions"><button class="btn sun" type="submit">'+e(t('recordPayment'))+'</button></div></form>';
 if(['offered','accepted','submitted','changes','approved'].includes(a.status))html+='<div class="modal-actions">'+btn('cancelWork','cancelWork','data-id="'+e(id)+'"','danger sm')+'</div>';
}
if(a.status==='paid')html+='<div class="mini-info"><strong>'+e(t('manualRecorded'))+'</strong><br>'+e(a.payment.reference)+' / '+date(a.payment.at)+(a.deal==='affiliate'?' / '+e(t('commissionAmount'))+' '+fm(a.payment.amount||0,a.fees.currency):'')+'</div>';
html+='<p class="tiny muted" style="margin-top:18px">'+e(t('noMoney'))+' / '+e(t('noFileUpload'))+'</p>';openModal(t('workDetail'),html,true);}
